"""add profile fields to users

Revision ID: 7ae6f74c0926
Revises: c9d9fe81175e
Create Date: 2026-08-04 10:59:14.448045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ae6f74c0926'
down_revision: Union[str, None] = 'c9d9fe81175e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expenses', 'property_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('users', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('dob', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('employment_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'employment_type')
    op.drop_column('users', 'address')
    op.drop_column('users', 'dob')
    op.drop_column('users', 'gender')
    op.alter_column('expenses', 'property_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
