"""Add StaffDepartment model

Revision ID: 85b290ae1f03
Revises: d1b1ff547d07
Create Date: 2026-08-17 14:18:09.749516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85b290ae1f03'
down_revision: Union[str, None] = 'd1b1ff547d07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_departments',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('designations', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_staff_departments_id'), 'staff_departments', ['id'], unique=False)
    
    # Insert default departments
    import uuid
    import json
    
    defaults = {
        "Administration": ["Property Manager", "Warden"],
        "Accounts & Finance": ["Accountant"],
        "Security": ["Security Guard"],
        "Housekeeping": ["Cleaner"],
        "Maintenance": ["Electrician", "Plumber"],
        "Reception / Front Desk": ["Receptionist"],
        "Kitchen / Mess": ["Cook"]
    }
    
    bind = op.get_bind()
    for dept, desigs in defaults.items():
        bind.execute(
            sa.text(
                "INSERT INTO staff_departments (id, name, designations) "
                "VALUES (:id, :name, CAST(:designations AS json)) "
                "ON CONFLICT (name) DO NOTHING"
            ).bindparams(
                id=uuid.uuid4(),
                name=dept,
                designations=json.dumps(desigs)
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_departments_id'), table_name='staff_departments')
    op.drop_table('staff_departments')
    # ### end Alembic commands ###
