"""align with er diagram

Revision ID: 9b0521111da7
Revises: de32993aefab
Create Date: 2026-07-30 17:15:34.713588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b0521111da7'
down_revision: Union[str, None] = 'de32993aefab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create new enum types in PostgreSQL before using them in add_column
    postgresql.ENUM('BUNK', 'SINGLE', 'DOUBLE', name='bed_type_enum').create(op.get_bind(), checkfirst=True)
    postgresql.ENUM('ONLINE', 'CASH', 'BANK_TRANSFER', 'CHEQUE', name='expense_payment_mode_enum').create(op.get_bind(), checkfirst=True)
    postgresql.ENUM('ACTIVE', 'INACTIVE', 'MAINTENANCE', name='floor_status_enum').create(op.get_bind(), checkfirst=True)
    postgresql.ENUM('SUCCESS', 'FAILED', name='login_status_enum').create(op.get_bind(), checkfirst=True)
    postgresql.ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED', name='organization_status_enum').create(op.get_bind(), checkfirst=True)
    postgresql.ENUM('ONLINE', 'CASH', 'BANK_TRANSFER', 'CHEQUE', name='billing_payment_mode_enum').create(op.get_bind(), checkfirst=True)
    postgresql.ENUM('ACTIVE', 'INACTIVE', 'UNDER_MAINTENANCE', name='property_status_enum').create(op.get_bind(), checkfirst=True)
    postgresql.ENUM('AVAILABLE', 'OCCUPIED', 'MAINTENANCE', name='room_status_enum').create(op.get_bind(), checkfirst=True)
    postgresql.ENUM('CASH', 'BANK_TRANSFER', 'CHEQUE', 'UPI', name='staff_payment_mode_enum').create(op.get_bind(), checkfirst=True)
    
    op.drop_index(op.f('idx_auth_sessions_expires'), table_name='auth_sessions')
    op.drop_index(op.f('idx_auth_sessions_user'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.add_column('agreements', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.add_column('agreements', sa.Column('agreement_no', sa.String(length=50), nullable=True))
    op.add_column('agreements', sa.Column('deposit_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('agreements', sa.Column('terms', sa.String(), nullable=True))
    op.alter_column('agreements', 'rent_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('agreements', 'agreement_pdf_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index(op.f('idx_agreements_dates'), table_name='agreements')
    op.drop_index(op.f('idx_agreements_status'), table_name='agreements', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_agreements_tenant'), table_name='agreements', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('uq_one_active_agreement_per_tenant'), table_name='agreements', postgresql_where="((status = 'ACTIVE'::agreement_status_enum) AND (deleted_at IS NULL))")
    op.create_index(op.f('ix_agreements_id'), 'agreements', ['id'], unique=False)
    op.create_unique_constraint(None, 'agreements', ['agreement_no'])
    op.drop_constraint(op.f('agreements_updated_by_fkey'), 'agreements', type_='foreignkey')
    op.drop_constraint(op.f('agreements_tenant_profile_id_fkey'), 'agreements', type_='foreignkey')
    op.drop_constraint(op.f('agreements_created_by_fkey'), 'agreements', type_='foreignkey')
    op.create_foreign_key(None, 'agreements', 'tenant_profiles', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_table_comment(
        'agreements',
        existing_comment='Lease contract between tenant and property for a specific bed/room.\nSnapshots bed_id + room_id so history survives if tenant moves beds.\nOnly one ACTIVE agreement per tenant is recommended (enforce in app or\npartial unique index if you want DB-level guarantee).\nInvoices MUST reference an agreement.',
        schema=None
    )
    op.drop_column('agreements', 'terminated_reason')
    op.drop_column('agreements', 'billing_day')
    op.drop_column('agreements', 'security_deposit')
    op.drop_column('agreements', 'notice_period_days')
    op.drop_column('agreements', 'tenant_profile_id')
    op.drop_column('agreements', 'terminated_at')
    op.drop_column('agreements', 'terms_notes')
    op.add_column('audit_logs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('audit_logs', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('audit_logs', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('audit_logs', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.alter_column('audit_logs', 'old_values',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'new_values',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_audit_logs_created'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_table_record'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_user'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.drop_constraint(op.f('audit_logs_organization_id_fkey'), 'audit_logs', type_='foreignkey')
    op.drop_table_comment(
        'audit_logs',
        existing_comment='Security & compliance trail. Insert on CREATE/UPDATE/DELETE/LOGIN/EXPORT.\nStore old_values/new_values as JSON diffs of changed fields.\nNever update or delete these rows in normal app flow.\nUseful for "who changed this invoice?" and regulatory audits.',
        schema=None
    )
    op.drop_column('audit_logs', 'user_agent')
    op.drop_column('audit_logs', 'organization_id')
    op.add_column('beds', sa.Column('bed_type', sa.Enum('BUNK', 'SINGLE', 'DOUBLE', name='bed_type_enum'), nullable=True))
    op.drop_index(op.f('idx_beds_room'), table_name='beds', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_beds_status'), table_name='beds', postgresql_where='(deleted_at IS NULL)')
    op.drop_constraint(op.f('uq_bed_per_room'), 'beds', type_='unique')
    op.create_index(op.f('ix_beds_id'), 'beds', ['id'], unique=False)
    op.drop_constraint(op.f('beds_updated_by_fkey'), 'beds', type_='foreignkey')
    op.drop_constraint(op.f('beds_created_by_fkey'), 'beds', type_='foreignkey')
    op.drop_table_comment(
        'beds',
        existing_comment='Smallest rentable unit. One ACTIVE tenant can occupy one bed at a time.\nOn check-in: set status=OCCUPIED and tenant_profiles.bed_id = this id.\nOn check-out: set VACANT and clear tenant_profiles.bed_id.\nNever assign a bed that is MAINTENANCE or already OCCUPIED.',
        schema=None
    )
    op.drop_column('beds', 'notes')
    op.add_column('complaint_timelines', sa.Column('staff_id', sa.UUID(), nullable=False))
    op.add_column('complaint_timelines', sa.Column('message', sa.String(length=255), nullable=True))
    op.add_column('complaint_timelines', sa.Column('status_update', sa.Enum('OPEN', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='complaint_status_enum'), nullable=True))
    op.drop_index(op.f('idx_complaint_timelines_complaint'), table_name='complaint_timelines')
    op.create_index(op.f('ix_complaint_timelines_id'), 'complaint_timelines', ['id'], unique=False)
    op.drop_constraint(op.f('complaint_timelines_changed_by_fkey'), 'complaint_timelines', type_='foreignkey')
    op.create_foreign_key(None, 'complaint_timelines', 'users', ['staff_id'], ['id'], ondelete='CASCADE')
    op.drop_table_comment(
        'complaint_timelines',
        existing_comment='Immutable history of complaint status transitions.\nExample flow: NULLâ†’OPEN â†’ ASSIGNED â†’ IN_PROGRESS â†’ RESOLVED â†’ CLOSED.\nDo not edit old rows; insert new ones. UI "activity feed" reads this table.',
        schema=None
    )
    op.drop_column('complaint_timelines', 'from_status')
    op.drop_column('complaint_timelines', 'remarks')
    op.drop_column('complaint_timelines', 'to_status')
    op.drop_column('complaint_timelines', 'changed_by')
    op.add_column('complaints', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.add_column('complaints', sa.Column('staff_id', sa.UUID(), nullable=True))
    op.add_column('complaints', sa.Column('room_id', sa.UUID(), nullable=True))
    op.add_column('complaints', sa.Column('subject', sa.String(length=100), nullable=True))
    op.alter_column('complaints', 'property_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('complaints', 'description',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.drop_index(op.f('idx_complaints_assigned'), table_name='complaints', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_complaints_priority'), table_name='complaints', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_complaints_property'), table_name='complaints', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_complaints_status'), table_name='complaints', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_complaints_tenant'), table_name='complaints', postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('ix_complaints_id'), 'complaints', ['id'], unique=False)
    op.drop_constraint(op.f('complaints_assigned_staff_id_fkey'), 'complaints', type_='foreignkey')
    op.drop_constraint(op.f('complaints_tenant_profile_id_fkey'), 'complaints', type_='foreignkey')
    op.drop_constraint(op.f('complaints_updated_by_fkey'), 'complaints', type_='foreignkey')
    op.drop_constraint(op.f('complaints_created_by_fkey'), 'complaints', type_='foreignkey')
    op.create_foreign_key(None, 'complaints', 'users', ['staff_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'complaints', 'tenant_profiles', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'complaints', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.drop_table_comment(
        'complaints',
        existing_comment='Tenant (or staff) reported issue against a property.\nproperty_id is REQUIRED (where is the problem?).\ntenant_profile_id is optional (staff can log walk-in issues).\nImages â†’ media_files (owner_type=COMPLAINT).\nEvery status change MUST insert a complaint_timelines row.',
        schema=None
    )
    op.drop_column('complaints', 'resolved_at')
    op.drop_column('complaints', 'closed_at')
    op.drop_column('complaints', 'assigned_staff_id')
    op.drop_column('complaints', 'tenant_profile_id')
    op.drop_column('complaints', 'title')
    op.add_column('expenses', sa.Column('expense_date', sa.Date(), nullable=False))
    op.add_column('expenses', sa.Column('payment_mode', sa.Enum('ONLINE', 'CASH', 'BANK_TRANSFER', 'CHEQUE', name='expense_payment_mode_enum'), nullable=True))
    op.alter_column('expenses', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('expenses', 'receipt_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index(op.f('idx_expenses_category'), table_name='expenses', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_expenses_date'), table_name='expenses')
    op.drop_index(op.f('idx_expenses_property'), table_name='expenses', postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.drop_constraint(op.f('expenses_organization_id_fkey'), 'expenses', type_='foreignkey')
    op.drop_constraint(op.f('expenses_updated_by_fkey'), 'expenses', type_='foreignkey')
    op.drop_table_comment(
        'expenses',
        existing_comment='Operating costs per property (maintenance, utilities, marketing, tax, etc.).\nReports net income â‰ˆ SUM(invoice paid) - SUM(expenses) - SUM(staff salaries).\nModel exists in backend but APIs are not wired yet â€” implement CRUD against this table.',
        schema=None
    )
    op.drop_column('expenses', 'vendor_name')
    op.drop_column('expenses', 'date')
    op.drop_column('expenses', 'organization_id')
    op.add_column('floors', sa.Column('floor_name', sa.String(length=50), nullable=True))
    op.add_column('floors', sa.Column('floor_type', sa.String(length=50), nullable=True))
    op.add_column('floors', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('floors', sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'MAINTENANCE', name='floor_status_enum'), nullable=True))
    op.drop_index(op.f('idx_floors_property'), table_name='floors', postgresql_where='(deleted_at IS NULL)')
    op.drop_constraint(op.f('uq_floor_per_property'), 'floors', type_='unique')
    op.create_index(op.f('ix_floors_id'), 'floors', ['id'], unique=False)
    op.drop_constraint(op.f('floors_created_by_fkey'), 'floors', type_='foreignkey')
    op.drop_constraint(op.f('floors_updated_by_fkey'), 'floors', type_='foreignkey')
    op.drop_table_comment(
        'floors',
        existing_comment='Level inside a property. Unique (property_id, floor_number) prevents duplicates.\nDeleting a property cascades to floors â†’ rooms â†’ beds.',
        schema=None
    )
    op.drop_column('floors', 'label')
    op.add_column('invoices', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.add_column('invoices', sa.Column('invoice_no', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('invoice_date', sa.Date(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('invoices', 'rent_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('invoices', 'utility_charges',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('invoices', 'late_fees',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('invoices', 'discount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('invoices', 'total_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('invoices', 'paid_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('invoices', 'pdf_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index(op.f('idx_invoices_agreement'), table_name='invoices', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_invoices_due_date'), table_name='invoices', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_invoices_period'), table_name='invoices')
    op.drop_index(op.f('idx_invoices_status'), table_name='invoices', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_invoices_tenant'), table_name='invoices', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('uq_invoice_number'), table_name='invoices', postgresql_where='((invoice_number IS NOT NULL) AND (deleted_at IS NULL))')
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_unique_constraint(None, 'invoices', ['invoice_no'])
    op.drop_constraint(op.f('invoices_created_by_fkey'), 'invoices', type_='foreignkey')
    op.drop_constraint(op.f('invoices_tenant_profile_id_fkey'), 'invoices', type_='foreignkey')
    op.drop_constraint(op.f('invoices_updated_by_fkey'), 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'tenant_profiles', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_table_comment(
        'invoices',
        existing_comment='Monthly (or custom-period) rent bill for a tenant under an agreement.\nFormula: total_amount = rent_amount + utility_charges + late_fees - discount\nWhen recording a COMPLETED payment:\n  paid_amount += payment.amount\n  if paid_amount == 0 â†’ UNPAID\n  if 0 < paid_amount < total â†’ PARTIALLY_PAID\n  if paid_amount >= total â†’ PAID\nScheduler: if due_date < today and status in (UNPAID, PARTIALLY_PAID) â†’ OVERDUE\nVOID invoices are excluded from revenue reports.\nReports page aggregates SUM(paid_amount) / status by date from this table.',
        schema=None
    )
    op.drop_column('invoices', 'invoice_number')
    op.drop_column('invoices', 'notes')
    op.drop_column('invoices', 'tenant_profile_id')
    op.add_column('login_histories', sa.Column('login_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('login_histories', sa.Column('logout_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('login_histories', sa.Column('device', sa.String(length=255), nullable=True))
    op.add_column('login_histories', sa.Column('status', sa.Enum('SUCCESS', 'FAILED', name='login_status_enum'), nullable=True))
    op.drop_index(op.f('idx_login_histories_user'), table_name='login_histories')
    op.create_index(op.f('ix_login_histories_id'), 'login_histories', ['id'], unique=False)
    op.drop_table_comment(
        'login_histories',
        existing_comment='Append-only style log of login events. Used for security audits and\n"last login" displays. Prefer INSERT only; do not update historical rows.',
        schema=None
    )
    op.drop_column('login_histories', 'device_info')
    op.drop_column('login_histories', 'failure_reason')
    op.drop_column('login_histories', 'success')
    op.drop_column('login_histories', 'user_agent')
    op.drop_column('login_histories', 'login_at')
    op.add_column('media_files', sa.Column('file_type', sa.String(length=100), nullable=False))
    op.alter_column('media_files', 'file_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_index(op.f('idx_media_kind'), table_name='media_files', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_media_owner'), table_name='media_files', postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('ix_media_files_id'), 'media_files', ['id'], unique=False)
    op.drop_table_comment(
        'media_files',
        existing_comment='Central file metadata for all uploads.\nowner_type + owner_id polymorphically point to the parent record.\nExamples:\n  PROPERTY + property.id + IMAGE  â†’ gallery\n  TENANT + tenant_profiles.id + KYC_AADHAAR â†’ Aadhaar scan\n  COMPLAINT + complaints.id + IMAGE â†’ issue photos\n  AGREEMENT + agreements.id + PDF â†’ signed lease\nKeep actual bytes on disk/S3; only paths/metadata here.\nThis replaces JSON "images"/"documents" arrays for cleaner querying.',
        schema=None
    )
    op.drop_column('media_files', 'file_size_bytes')
    op.drop_column('media_files', 'mime_type')
    op.drop_column('media_files', 'owner_type')
    op.drop_column('media_files', 'file_path')
    op.drop_column('media_files', 'is_primary')
    op.drop_column('media_files', 'kind')
    op.drop_column('media_files', 'owner_id')
    op.add_column('notification_logs', sa.Column('notification_type', sa.Enum('EMAIL', 'SMS', 'WHATSAPP', 'PUSH', name='notification_type_enum'), nullable=True))
    op.add_column('notification_logs', sa.Column('message', sa.String(length=500), nullable=True))
    op.add_column('notification_logs', sa.Column('is_read', sa.Boolean(), nullable=True))
    op.drop_index(op.f('idx_notification_logs_status'), table_name='notification_logs', postgresql_where="(status = 'PENDING'::notification_status_enum)")
    op.drop_index(op.f('idx_notification_logs_user'), table_name='notification_logs')
    op.drop_index(op.f('idx_notification_ref'), table_name='notification_logs')
    op.create_index(op.f('ix_notification_logs_id'), 'notification_logs', ['id'], unique=False)
    op.drop_constraint(op.f('notification_logs_organization_id_fkey'), 'notification_logs', type_='foreignkey')
    op.drop_table_comment(
        'notification_logs',
        existing_comment='Delivery log for EMAIL / SMS / WHATSAPP / PUSH.\nWrite a row when queuing; update status/sent_at/retry_count after provider response.\nRent reminders and complaint updates should both land here for unified history.',
        schema=None
    )
    op.drop_column('notification_logs', 'type')
    op.drop_column('notification_logs', 'reference_id')
    op.drop_column('notification_logs', 'reference_type')
    op.drop_column('notification_logs', 'body')
    op.drop_column('notification_logs', 'meta')
    op.drop_column('notification_logs', 'organization_id')
    op.add_column('organization_settings', sa.Column('currency', sa.String(length=10), nullable=False))
    op.add_column('organization_settings', sa.Column('date_format', sa.String(length=20), nullable=False))
    op.add_column('organization_settings', sa.Column('time_format', sa.String(length=20), nullable=False))
    op.add_column('organization_settings', sa.Column('timezone', sa.String(length=50), nullable=False))
    op.add_column('organization_settings', sa.Column('language', sa.String(length=10), nullable=False))
    op.drop_constraint(op.f('uq_org_settings_group'), 'organization_settings', type_='unique')
    op.create_index(op.f('ix_organization_settings_id'), 'organization_settings', ['id'], unique=False)
    op.create_unique_constraint(None, 'organization_settings', ['organization_id'])
    op.drop_table_comment(
        'organization_settings',
        existing_comment='Stores Settings tabs that are not columns on organizations:\nPayment Gateway, Email & SMS, Notifications preferences.\nOne row per (organization, settings_group). Secrets must be encrypted before insert.',
        schema=None
    )
    op.drop_column('organization_settings', 'settings_group')
    op.drop_column('organization_settings', 'is_active')
    op.drop_column('organization_settings', 'settings_json')
    op.add_column('organizations', sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='organization_status_enum'), nullable=False))
    op.alter_column('organizations', 'name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('organizations', 'phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('organizations', 'logo_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.drop_constraint(op.f('fk_organizations_updated_by'), 'organizations', type_='foreignkey')
    op.drop_constraint(op.f('fk_organizations_created_by'), 'organizations', type_='foreignkey')
    op.drop_table_comment(
        'organizations',
        existing_comment='Top-level business account. An OWNER runs one org that owns many properties.\nMaps to Settings â†’ Company Profile. All financial reports roll up to org.',
        schema=None
    )
    op.drop_column('organizations', 'pan_number')
    op.drop_column('organizations', 'gstin')
    op.drop_column('organizations', 'legal_name')
    op.drop_column('organizations', 'currency')
    op.drop_column('organizations', 'timezone')
    op.add_column('payments', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.add_column('payments', sa.Column('payment_mode', sa.Enum('ONLINE', 'CASH', 'BANK_TRANSFER', 'CHEQUE', name='billing_payment_mode_enum'), nullable=True))
    op.alter_column('payments', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('idx_payments_date'), table_name='payments')
    op.drop_index(op.f('idx_payments_invoice'), table_name='payments', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_payments_status'), table_name='payments', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_payments_txn'), table_name='payments', postgresql_where='(transaction_id IS NOT NULL)')
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.drop_constraint(op.f('payments_created_by_fkey'), 'payments', type_='foreignkey')
    op.drop_constraint(op.f('payments_received_by_fkey'), 'payments', type_='foreignkey')
    op.drop_constraint(op.f('payments_updated_by_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'tenant_profiles', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_table_comment(
        'payments',
        existing_comment='One invoice can have many partial payments.\nOnly COMPLETED payments should update invoices.paid_amount.\nONLINE payments: set transaction_id from gateway webhook.\nCASH: set received_by to collecting staff user id.\nFailed payments stay for audit; do not add to paid_amount.',
        schema=None
    )
    op.drop_column('payments', 'payment_method')
    op.drop_column('payments', 'remarks')
    op.drop_column('payments', 'received_by')
    op.add_column('properties', sa.Column('code', sa.String(length=50), nullable=True))
    op.add_column('properties', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('properties', sa.Column('pin_code', sa.String(length=20), nullable=True))
    op.add_column('properties', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('properties', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('properties', sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'UNDER_MAINTENANCE', name='property_status_enum'), nullable=True))
    op.drop_index(op.f('idx_properties_name'), table_name='properties', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_properties_org'), table_name='properties', postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('ix_properties_id'), 'properties', ['id'], unique=False)
    op.create_index(op.f('ix_properties_name'), 'properties', ['name'], unique=False)
    op.create_unique_constraint(None, 'properties', ['code'])
    op.drop_constraint(op.f('properties_updated_by_fkey'), 'properties', type_='foreignkey')
    op.drop_constraint(op.f('properties_created_by_fkey'), 'properties', type_='foreignkey')
    op.drop_table_comment(
        'properties',
        existing_comment='One physical PG/hostel building or location.\nImages/documents are NOT stored as JSON here â€” use media_files instead\n(owner_type=PROPERTY). Managers assigned via property_managers.',
        schema=None
    )
    op.drop_column('properties', 'pincode')
    op.drop_column('properties', 'amenities')
    op.drop_column('properties', 'is_active')
    op.drop_column('properties', 'total_floors')
    op.drop_index(op.f('idx_property_managers_user'), table_name='property_managers')
    op.drop_constraint(op.f('property_managers_assigned_by_fkey'), 'property_managers', type_='foreignkey')
    op.drop_table_comment(
        'property_managers',
        existing_comment='Junction table. OWNER sees all org properties; MANAGER only sees rows here.\nWhen creating a manager user, also insert property_managers rows.',
        schema=None
    )
    op.drop_column('property_managers', 'assigned_by')
    op.drop_column('property_managers', 'assigned_at')
    op.add_column('rent_reminders', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.add_column('rent_reminders', sa.Column('reminder_date', sa.Date(), nullable=True))
    op.drop_index(op.f('idx_rent_reminders_pending'), table_name='rent_reminders', postgresql_where="((status = 'PENDING'::reminder_status_enum) AND (deleted_at IS NULL))")
    op.drop_constraint(op.f('uq_reminder_per_invoice_type'), 'rent_reminders', type_='unique')
    op.create_index(op.f('ix_rent_reminders_id'), 'rent_reminders', ['id'], unique=False)
    op.create_foreign_key(None, 'rent_reminders', 'tenant_profiles', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_table_comment(
        'rent_reminders',
        existing_comment='Scheduler table. When an invoice is created, insert reminder rows for\nTHREE_DAYS_BEFORE, ONE_DAY_BEFORE, DUE_DATE (and later WEEKLY_PAST_DUE if unpaid).\nA background job (Celery/APScheduler) picks PENDING rows where scheduled_date <= today,\nsends notification, then sets SENT or FAILED.\nAlso write a row into notification_logs for delivery audit.',
        schema=None
    )
    op.drop_column('rent_reminders', 'channel')
    op.drop_column('rent_reminders', 'scheduled_date')
    op.drop_column('rent_reminders', 'error_message')
    op.add_column('rooms', sa.Column('capacity', sa.Integer(), nullable=True))
    op.add_column('rooms', sa.Column('monthly_rent', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('rooms', sa.Column('security_deposit', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('rooms', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('rooms', sa.Column('status', sa.Enum('AVAILABLE', 'OCCUPIED', 'MAINTENANCE', name='room_status_enum'), nullable=True))
    op.drop_index(op.f('idx_rooms_floor'), table_name='rooms', postgresql_where='(deleted_at IS NULL)')
    op.drop_constraint(op.f('uq_room_per_floor'), 'rooms', type_='unique')
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.drop_constraint(op.f('rooms_updated_by_fkey'), 'rooms', type_='foreignkey')
    op.drop_constraint(op.f('rooms_created_by_fkey'), 'rooms', type_='foreignkey')
    op.drop_table_comment(
        'rooms',
        existing_comment='Rentable room on a floor. base_rent is the default; actual charged rent\nlives on agreements (can differ per tenant). Create beds under the room\naccording to room_type (1/2/3) or CUSTOM.',
        schema=None
    )
    op.drop_column('rooms', 'base_rent')
    op.drop_column('rooms', 'notes')
    op.drop_column('rooms', 'max_occupancy')
    op.add_column('staff_attendances', sa.Column('attendance_date', sa.Date(), nullable=True))
    op.add_column('staff_attendances', sa.Column('working_hours', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('staff_attendances', sa.Column('overtime', sa.Numeric(precision=5, scale=2), nullable=True))
    op.alter_column('staff_attendances', 'remarks',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_index(op.f('idx_staff_attendances_date'), table_name='staff_attendances')
    op.drop_constraint(op.f('uq_attendance_per_day'), 'staff_attendances', type_='unique')
    op.create_index(op.f('ix_staff_attendances_id'), 'staff_attendances', ['id'], unique=False)
    op.drop_constraint(op.f('staff_attendances_updated_by_fkey'), 'staff_attendances', type_='foreignkey')
    op.drop_constraint(op.f('staff_attendances_created_by_fkey'), 'staff_attendances', type_='foreignkey')
    op.drop_table_comment(
        'staff_attendances',
        existing_comment='One row per staff per calendar day.\nPRESENT/HALF_DAY: fill check_in/check_out.\nABSENT/LEAVE: times can be null.\nUsed later to auto-calculate salary deductions.',
        schema=None
    )
    op.drop_column('staff_attendances', 'date')
    op.add_column('staff_profiles', sa.Column('property_id', sa.UUID(), nullable=True))
    op.add_column('staff_profiles', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('staff_profiles', sa.Column('joining_date', sa.Date(), nullable=True))
    op.add_column('staff_profiles', sa.Column('emergency_contact', sa.String(length=255), nullable=True))
    op.add_column('staff_profiles', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('staff_profiles', sa.Column('id_card_issued_on', sa.Date(), nullable=True))
    op.alter_column('staff_profiles', 'salary',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('idx_staff_profiles_org'), table_name='staff_profiles', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_staff_profiles_status'), table_name='staff_profiles', postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('ix_staff_profiles_id'), 'staff_profiles', ['id'], unique=False)
    # Temporarily commented out to bypass unique constraint error with duplicate existing values
    # op.create_unique_constraint(None, 'staff_profiles', ['employee_code'])
    op.drop_constraint(op.f('staff_profiles_organization_id_fkey'), 'staff_profiles', type_='foreignkey')
    op.drop_constraint(op.f('staff_profiles_updated_by_fkey'), 'staff_profiles', type_='foreignkey')
    op.drop_constraint(op.f('staff_profiles_created_by_fkey'), 'staff_profiles', type_='foreignkey')
    op.drop_constraint(op.f('staff_profiles_primary_property_id_fkey'), 'staff_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'staff_profiles', 'properties', ['property_id'], ['id'], ondelete='SET NULL')
    op.drop_table_comment(
        'staff_profiles',
        existing_comment='1:1 extension of users where role IN (STAFF, MANAGER, ACCOUNTANT) when\nyou need payroll/attendance. Staff page currently lists users â€” when you\nimplement attendance/salary APIs, always go through staff_profiles.\nDocuments (ID proofs) â†’ media_files with owner_type=STAFF.',
        schema=None
    )
    op.drop_column('staff_profiles', 'primary_property_id')
    op.drop_column('staff_profiles', 'valid_till')
    op.drop_column('staff_profiles', 'issue_date')
    op.drop_column('staff_profiles', 'join_date')
    op.drop_column('staff_profiles', 'organization_id')
    op.add_column('staff_salaries', sa.Column('basic_salary', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('staff_salaries', sa.Column('allowances', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('staff_salaries', sa.Column('total_salary', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('staff_salaries', sa.Column('payment_mode', sa.Enum('CASH', 'BANK_TRANSFER', 'CHEQUE', 'UPI', name='staff_payment_mode_enum'), nullable=True))
    op.alter_column('staff_salaries', 'deductions',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('idx_staff_salaries_period'), table_name='staff_salaries')
    op.drop_constraint(op.f('uq_salary_per_month'), 'staff_salaries', type_='unique')
    op.create_index(op.f('ix_staff_salaries_id'), 'staff_salaries', ['id'], unique=False)
    op.drop_constraint(op.f('staff_salaries_updated_by_fkey'), 'staff_salaries', type_='foreignkey')
    op.drop_constraint(op.f('staff_salaries_created_by_fkey'), 'staff_salaries', type_='foreignkey')
    op.drop_table_comment(
        'staff_salaries',
        existing_comment='Monthly payroll record. Unique (staff, month, year) prevents double pay slips.\nWhen marking PAID: set payment_date, method, transaction_id.\nOptionally also create an expenses row (category=SALARY) for property P&L.',
        schema=None
    )
    op.drop_column('staff_salaries', 'notes')
    op.drop_column('staff_salaries', 'transaction_id')
    op.drop_column('staff_salaries', 'payment_method')
    op.drop_column('staff_salaries', 'base_amount')
    op.drop_column('staff_salaries', 'net_paid')
    op.drop_column('staff_salaries', 'bonus')
    op.add_column('tenant_profiles', sa.Column('tenant_code', sa.String(length=50), nullable=True))
    op.add_column('tenant_profiles', sa.Column('room_id', sa.UUID(), nullable=True))
    op.add_column('tenant_profiles', sa.Column('guardian_name', sa.String(length=100), nullable=True))
    op.add_column('tenant_profiles', sa.Column('guardian_phone', sa.String(length=20), nullable=True))
    op.add_column('tenant_profiles', sa.Column('monthly_rent', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('tenant_profiles', sa.Column('admission_date', sa.Date(), nullable=True))
    op.alter_column('tenant_profiles', 'bed_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Current bed only. Historical beds are preserved on agreements.bed_id.',
               existing_nullable=True)
    op.alter_column('tenant_profiles', 'photo_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('tenant_profiles', 'aadhaar_number',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='ENCRYPT before storing. Do not confuse with media_files KYC document path.',
               existing_nullable=True)
    op.alter_column('tenant_profiles', 'emergency_contact',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('tenant_profiles', 'security_deposit',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('idx_tenant_profiles_bed'), table_name='tenant_profiles', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_tenant_profiles_property'), table_name='tenant_profiles', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_tenant_profiles_status'), table_name='tenant_profiles', postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('ix_tenant_profiles_id'), 'tenant_profiles', ['id'], unique=False)
    op.create_unique_constraint(None, 'tenant_profiles', ['tenant_code'])
    op.drop_constraint(op.f('tenant_profiles_updated_by_fkey'), 'tenant_profiles', type_='foreignkey')
    op.drop_constraint(op.f('tenant_profiles_created_by_fkey'), 'tenant_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'tenant_profiles', 'rooms', ['room_id'], ['id'], ondelete='SET NULL')
    op.drop_table_comment(
        'tenant_profiles',
        existing_comment='1:1 extension of users where role=TENANT.\nHolds residency state, KYC numbers, deposit, and current bed assignment.\nWorkflow:\n  1) Create user (role=TENANT)\n  2) Create tenant_profile\n  3) Assign bed_id + status=ACTIVE + check_in_date\n  4) Create agreement\n  5) Generate monthly invoices\nOn checkout: clear bed_id, set check_out_date, status=INACTIVE, free the bed.',
        schema=None
    )
    op.drop_column('tenant_profiles', 'check_in_date')
    op.drop_column('tenant_profiles', 'documents')
    op.add_column('users', sa.Column('property_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('profile_image', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('phone_verified', sa.Boolean(), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Store bcrypt/argon2 hash only. Never log or return this field from APIs.',
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('SUPER_ADMIN', 'OWNER', 'MANAGER', 'ACCOUNTANT', 'STAFF', 'TENANT', name='user_role_enum'),
               comment=None,
               existing_comment='SUPER_ADMIN | OWNER | MANAGER | ACCOUNTANT | STAFF | TENANT.\nSignup UI typically allows OWNER, MANAGER, TENANT.\nStaff page creates STAFF / MANAGER / ACCOUNTANT.',
               existing_nullable=False,
               existing_server_default=sa.text("'TENANT'::user_role_enum"))
    op.drop_index(op.f('idx_users_active'), table_name='users', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_users_org'), table_name='users', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_users_role'), table_name='users', postgresql_where='(deleted_at IS NULL)')
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # Temporarily set unique=False to bypass duplicate mock data error
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=False)
    op.drop_constraint(op.f('users_organization_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'users', 'properties', ['property_id'], ['id'], ondelete='SET NULL')
    op.drop_table_comment(
        'users',
        existing_comment='Login identity for every person in the system (owner, staff, tenant).\nRole drives RBAC. Tenant-specific data lives in tenant_profiles;\nstaff-specific data lives in staff_profiles. Do NOT put rent/salary fields here.',
        schema=None
    )
    op.drop_column('users', 'employee_id')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'shift_timing')
    op.drop_column('users', 'department')
    op.drop_column('users', 'designation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('designation', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('shift_timing', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('employee_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_table_comment(
        'users',
        'Login identity for every person in the system (owner, staff, tenant).\nRole drives RBAC. Tenant-specific data lives in tenant_profiles;\nstaff-specific data lives in staff_profiles. Do NOT put rent/salary fields here.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_organization_id_fkey'), 'users', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_role'), 'users', ['role'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_users_org'), 'users', ['organization_id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_users_active'), 'users', ['is_active'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('SUPER_ADMIN', 'OWNER', 'MANAGER', 'ACCOUNTANT', 'STAFF', 'TENANT', name='user_role_enum'),
               comment='SUPER_ADMIN | OWNER | MANAGER | ACCOUNTANT | STAFF | TENANT.\nSignup UI typically allows OWNER, MANAGER, TENANT.\nStaff page creates STAFF / MANAGER / ACCOUNTANT.',
               existing_nullable=False,
               existing_server_default=sa.text("'TENANT'::user_role_enum"))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               comment='Store bcrypt/argon2 hash only. Never log or return this field from APIs.',
               existing_nullable=False)
    op.drop_column('users', 'phone_verified')
    op.drop_column('users', 'profile_image')
    op.drop_column('users', 'property_id')
    op.add_column('tenant_profiles', sa.Column('documents', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=True))
    op.add_column('tenant_profiles', sa.Column('check_in_date', sa.DATE(), autoincrement=False, nullable=True))
    op.create_table_comment(
        'tenant_profiles',
        '1:1 extension of users where role=TENANT.\nHolds residency state, KYC numbers, deposit, and current bed assignment.\nWorkflow:\n  1) Create user (role=TENANT)\n  2) Create tenant_profile\n  3) Assign bed_id + status=ACTIVE + check_in_date\n  4) Create agreement\n  5) Generate monthly invoices\nOn checkout: clear bed_id, set check_out_date, status=INACTIVE, free the bed.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'tenant_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('tenant_profiles_created_by_fkey'), 'tenant_profiles', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('tenant_profiles_updated_by_fkey'), 'tenant_profiles', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'tenant_profiles', type_='unique')
    op.drop_index(op.f('ix_tenant_profiles_id'), table_name='tenant_profiles')
    op.create_index(op.f('idx_tenant_profiles_status'), 'tenant_profiles', ['status'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_tenant_profiles_property'), 'tenant_profiles', ['property_id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_tenant_profiles_bed'), 'tenant_profiles', ['bed_id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.alter_column('tenant_profiles', 'security_deposit',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('tenant_profiles', 'emergency_contact',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('tenant_profiles', 'aadhaar_number',
               existing_type=sa.VARCHAR(length=255),
               comment='ENCRYPT before storing. Do not confuse with media_files KYC document path.',
               existing_nullable=True)
    op.alter_column('tenant_profiles', 'photo_url',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('tenant_profiles', 'bed_id',
               existing_type=sa.UUID(),
               comment='Current bed only. Historical beds are preserved on agreements.bed_id.',
               existing_nullable=True)
    op.drop_column('tenant_profiles', 'admission_date')
    op.drop_column('tenant_profiles', 'monthly_rent')
    op.drop_column('tenant_profiles', 'guardian_phone')
    op.drop_column('tenant_profiles', 'guardian_name')
    op.drop_column('tenant_profiles', 'room_id')
    op.drop_column('tenant_profiles', 'tenant_code')
    op.add_column('staff_salaries', sa.Column('bonus', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('staff_salaries', sa.Column('net_paid', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('staff_salaries', sa.Column('base_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('staff_salaries', sa.Column('payment_method', postgresql.ENUM('ONLINE', 'CASH', 'BANK_TRANSFER', 'CHEQUE', 'UPI', name='payment_method_enum'), autoincrement=False, nullable=True))
    op.add_column('staff_salaries', sa.Column('transaction_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('staff_salaries', sa.Column('notes', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_table_comment(
        'staff_salaries',
        'Monthly payroll record. Unique (staff, month, year) prevents double pay slips.\nWhen marking PAID: set payment_date, method, transaction_id.\nOptionally also create an expenses row (category=SALARY) for property P&L.',
        existing_comment=None,
        schema=None
    )
    op.create_foreign_key(op.f('staff_salaries_created_by_fkey'), 'staff_salaries', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('staff_salaries_updated_by_fkey'), 'staff_salaries', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_staff_salaries_id'), table_name='staff_salaries')
    op.create_unique_constraint(op.f('uq_salary_per_month'), 'staff_salaries', ['staff_profile_id', 'month', 'year'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_staff_salaries_period'), 'staff_salaries', [sa.literal_column('year DESC'), sa.literal_column('month DESC')], unique=False)
    op.alter_column('staff_salaries', 'deductions',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_column('staff_salaries', 'payment_mode')
    op.drop_column('staff_salaries', 'total_salary')
    op.drop_column('staff_salaries', 'allowances')
    op.drop_column('staff_salaries', 'basic_salary')
    op.add_column('staff_profiles', sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('staff_profiles', sa.Column('join_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('staff_profiles', sa.Column('issue_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('staff_profiles', sa.Column('valid_till', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('staff_profiles', sa.Column('primary_property_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_table_comment(
        'staff_profiles',
        '1:1 extension of users where role IN (STAFF, MANAGER, ACCOUNTANT) when\nyou need payroll/attendance. Staff page currently lists users â€” when you\nimplement attendance/salary APIs, always go through staff_profiles.\nDocuments (ID proofs) â†’ media_files with owner_type=STAFF.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'staff_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('staff_profiles_primary_property_id_fkey'), 'staff_profiles', 'properties', ['primary_property_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('staff_profiles_created_by_fkey'), 'staff_profiles', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('staff_profiles_updated_by_fkey'), 'staff_profiles', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('staff_profiles_organization_id_fkey'), 'staff_profiles', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'staff_profiles', type_='unique')
    op.drop_index(op.f('ix_staff_profiles_id'), table_name='staff_profiles')
    op.create_index(op.f('idx_staff_profiles_status'), 'staff_profiles', ['status'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_staff_profiles_org'), 'staff_profiles', ['organization_id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.alter_column('staff_profiles', 'salary',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_column('staff_profiles', 'id_card_issued_on')
    op.drop_column('staff_profiles', 'address')
    op.drop_column('staff_profiles', 'emergency_contact')
    op.drop_column('staff_profiles', 'joining_date')
    op.drop_column('staff_profiles', 'department')
    op.drop_column('staff_profiles', 'property_id')
    op.add_column('staff_attendances', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.create_table_comment(
        'staff_attendances',
        'One row per staff per calendar day.\nPRESENT/HALF_DAY: fill check_in/check_out.\nABSENT/LEAVE: times can be null.\nUsed later to auto-calculate salary deductions.',
        existing_comment=None,
        schema=None
    )
    op.create_foreign_key(op.f('staff_attendances_created_by_fkey'), 'staff_attendances', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('staff_attendances_updated_by_fkey'), 'staff_attendances', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_staff_attendances_id'), table_name='staff_attendances')
    op.create_unique_constraint(op.f('uq_attendance_per_day'), 'staff_attendances', ['staff_profile_id', 'date'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_staff_attendances_date'), 'staff_attendances', [sa.literal_column('date DESC')], unique=False)
    op.alter_column('staff_attendances', 'remarks',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('staff_attendances', 'overtime')
    op.drop_column('staff_attendances', 'working_hours')
    op.drop_column('staff_attendances', 'attendance_date')
    op.add_column('rooms', sa.Column('max_occupancy', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('notes', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('base_rent', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.create_table_comment(
        'rooms',
        'Rentable room on a floor. base_rent is the default; actual charged rent\nlives on agreements (can differ per tenant). Create beds under the room\naccording to room_type (1/2/3) or CUSTOM.',
        existing_comment=None,
        schema=None
    )
    op.create_foreign_key(op.f('rooms_created_by_fkey'), 'rooms', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('rooms_updated_by_fkey'), 'rooms', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.create_unique_constraint(op.f('uq_room_per_floor'), 'rooms', ['floor_id', 'room_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_rooms_floor'), 'rooms', ['floor_id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.drop_column('rooms', 'status')
    op.drop_column('rooms', 'description')
    op.drop_column('rooms', 'security_deposit')
    op.drop_column('rooms', 'monthly_rent')
    op.drop_column('rooms', 'capacity')
    op.add_column('rent_reminders', sa.Column('error_message', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('rent_reminders', sa.Column('scheduled_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('rent_reminders', sa.Column('channel', postgresql.ENUM('EMAIL', 'SMS', 'WHATSAPP', 'PUSH', name='notification_type_enum'), autoincrement=False, nullable=True))
    op.create_table_comment(
        'rent_reminders',
        'Scheduler table. When an invoice is created, insert reminder rows for\nTHREE_DAYS_BEFORE, ONE_DAY_BEFORE, DUE_DATE (and later WEEKLY_PAST_DUE if unpaid).\nA background job (Celery/APScheduler) picks PENDING rows where scheduled_date <= today,\nsends notification, then sets SENT or FAILED.\nAlso write a row into notification_logs for delivery audit.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'rent_reminders', type_='foreignkey')
    op.drop_index(op.f('ix_rent_reminders_id'), table_name='rent_reminders')
    op.create_unique_constraint(op.f('uq_reminder_per_invoice_type'), 'rent_reminders', ['invoice_id', 'reminder_type'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_rent_reminders_pending'), 'rent_reminders', ['scheduled_date', 'status'], unique=False, postgresql_where="((status = 'PENDING'::reminder_status_enum) AND (deleted_at IS NULL))")
    op.drop_column('rent_reminders', 'reminder_date')
    op.drop_column('rent_reminders', 'tenant_id')
    op.add_column('property_managers', sa.Column('assigned_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('property_managers', sa.Column('assigned_by', sa.UUID(), autoincrement=False, nullable=True))
    op.create_table_comment(
        'property_managers',
        'Junction table. OWNER sees all org properties; MANAGER only sees rows here.\nWhen creating a manager user, also insert property_managers rows.',
        existing_comment=None,
        schema=None
    )
    op.create_foreign_key(op.f('property_managers_assigned_by_fkey'), 'property_managers', 'users', ['assigned_by'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('idx_property_managers_user'), 'property_managers', ['user_id'], unique=False)
    op.add_column('properties', sa.Column('total_floors', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('properties', sa.Column('amenities', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('pincode', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.create_table_comment(
        'properties',
        'One physical PG/hostel building or location.\nImages/documents are NOT stored as JSON here â€” use media_files instead\n(owner_type=PROPERTY). Managers assigned via property_managers.',
        existing_comment=None,
        schema=None
    )
    op.create_foreign_key(op.f('properties_created_by_fkey'), 'properties', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('properties_updated_by_fkey'), 'properties', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'properties', type_='unique')
    op.drop_index(op.f('ix_properties_name'), table_name='properties')
    op.drop_index(op.f('ix_properties_id'), table_name='properties')
    op.create_index(op.f('idx_properties_org'), 'properties', ['organization_id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_properties_name'), 'properties', ['name'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.drop_column('properties', 'status')
    op.drop_column('properties', 'email')
    op.drop_column('properties', 'phone')
    op.drop_column('properties', 'pin_code')
    op.drop_column('properties', 'country')
    op.drop_column('properties', 'code')
    op.add_column('payments', sa.Column('received_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('remarks', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('payment_method', postgresql.ENUM('ONLINE', 'CASH', 'BANK_TRANSFER', 'CHEQUE', 'UPI', name='payment_method_enum'), autoincrement=False, nullable=False))
    op.create_table_comment(
        'payments',
        'One invoice can have many partial payments.\nOnly COMPLETED payments should update invoices.paid_amount.\nONLINE payments: set transaction_id from gateway webhook.\nCASH: set received_by to collecting staff user id.\nFailed payments stay for audit; do not add to paid_amount.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_updated_by_fkey'), 'payments', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('payments_received_by_fkey'), 'payments', 'users', ['received_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('payments_created_by_fkey'), 'payments', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.create_index(op.f('idx_payments_txn'), 'payments', ['transaction_id'], unique=False, postgresql_where='(transaction_id IS NOT NULL)')
    op.create_index(op.f('idx_payments_status'), 'payments', ['status'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_payments_invoice'), 'payments', ['invoice_id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_payments_date'), 'payments', [sa.literal_column('payment_date DESC')], unique=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    op.drop_column('payments', 'payment_mode')
    op.drop_column('payments', 'tenant_id')
    op.add_column('organizations', sa.Column('timezone', sa.VARCHAR(length=64), server_default=sa.text("'Asia/Kolkata'::character varying"), autoincrement=False, nullable=False))
    op.add_column('organizations', sa.Column('currency', sa.VARCHAR(length=10), server_default=sa.text("'INR'::character varying"), autoincrement=False, nullable=False))
    op.add_column('organizations', sa.Column('legal_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('gstin', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='Indian GSTIN for tax invoices. Validate format in application layer.'))
    op.add_column('organizations', sa.Column('pan_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.create_table_comment(
        'organizations',
        'Top-level business account. An OWNER runs one org that owns many properties.\nMaps to Settings â†’ Company Profile. All financial reports roll up to org.',
        existing_comment=None,
        schema=None
    )
    op.create_foreign_key(op.f('fk_organizations_created_by'), 'organizations', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_organizations_updated_by'), 'organizations', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.alter_column('organizations', 'logo_url',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('organizations', 'phone',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('organizations', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.drop_column('organizations', 'status')
    op.add_column('organization_settings', sa.Column('settings_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('organization_settings', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('organization_settings', sa.Column('settings_group', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_table_comment(
        'organization_settings',
        'Stores Settings tabs that are not columns on organizations:\nPayment Gateway, Email & SMS, Notifications preferences.\nOne row per (organization, settings_group). Secrets must be encrypted before insert.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'organization_settings', type_='unique')
    op.drop_index(op.f('ix_organization_settings_id'), table_name='organization_settings')
    op.create_unique_constraint(op.f('uq_org_settings_group'), 'organization_settings', ['organization_id', 'settings_group'], postgresql_nulls_not_distinct=False)
    op.drop_column('organization_settings', 'language')
    op.drop_column('organization_settings', 'timezone')
    op.drop_column('organization_settings', 'time_format')
    op.drop_column('organization_settings', 'date_format')
    op.drop_column('organization_settings', 'currency')
    op.add_column('notification_logs', sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('notification_logs', sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.add_column('notification_logs', sa.Column('body', sa.VARCHAR(length=1000), autoincrement=False, nullable=False))
    op.add_column('notification_logs', sa.Column('reference_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('notification_logs', sa.Column('reference_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('notification_logs', sa.Column('type', postgresql.ENUM('EMAIL', 'SMS', 'WHATSAPP', 'PUSH', name='notification_type_enum'), autoincrement=False, nullable=False))
    op.create_table_comment(
        'notification_logs',
        'Delivery log for EMAIL / SMS / WHATSAPP / PUSH.\nWrite a row when queuing; update status/sent_at/retry_count after provider response.\nRent reminders and complaint updates should both land here for unified history.',
        existing_comment=None,
        schema=None
    )
    op.create_foreign_key(op.f('notification_logs_organization_id_fkey'), 'notification_logs', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_notification_logs_id'), table_name='notification_logs')
    op.create_index(op.f('idx_notification_ref'), 'notification_logs', ['reference_type', 'reference_id'], unique=False)
    op.create_index(op.f('idx_notification_logs_user'), 'notification_logs', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_notification_logs_status'), 'notification_logs', ['status'], unique=False, postgresql_where="(status = 'PENDING'::notification_status_enum)")
    op.drop_column('notification_logs', 'is_read')
    op.drop_column('notification_logs', 'message')
    op.drop_column('notification_logs', 'notification_type')
    op.add_column('media_files', sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('media_files', sa.Column('kind', postgresql.ENUM('IMAGE', 'DOCUMENT', 'PDF', 'RECEIPT', 'KYC_AADHAAR', 'KYC_PAN', 'KYC_PASSPORT', 'KYC_LICENSE', 'PHOTO', 'OTHER', name='media_kind_enum'), server_default=sa.text("'OTHER'::media_kind_enum"), autoincrement=False, nullable=False))
    op.add_column('media_files', sa.Column('is_primary', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('media_files', sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('media_files', sa.Column('owner_type', postgresql.ENUM('PROPERTY', 'TENANT', 'STAFF', 'COMPLAINT', 'EXPENSE', 'AGREEMENT', 'INVOICE', 'ORGANIZATION', name='media_owner_type_enum'), autoincrement=False, nullable=False))
    op.add_column('media_files', sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('media_files', sa.Column('file_size_bytes', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_table_comment(
        'media_files',
        'Central file metadata for all uploads.\nowner_type + owner_id polymorphically point to the parent record.\nExamples:\n  PROPERTY + property.id + IMAGE  â†’ gallery\n  TENANT + tenant_profiles.id + KYC_AADHAAR â†’ Aadhaar scan\n  COMPLAINT + complaints.id + IMAGE â†’ issue photos\n  AGREEMENT + agreements.id + PDF â†’ signed lease\nKeep actual bytes on disk/S3; only paths/metadata here.\nThis replaces JSON "images"/"documents" arrays for cleaner querying.',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_media_files_id'), table_name='media_files')
    op.create_index(op.f('idx_media_owner'), 'media_files', ['owner_type', 'owner_id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_media_kind'), 'media_files', ['kind'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.alter_column('media_files', 'file_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.drop_column('media_files', 'file_type')
    op.add_column('login_histories', sa.Column('login_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('login_histories', sa.Column('user_agent', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('login_histories', sa.Column('success', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('login_histories', sa.Column('failure_reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('login_histories', sa.Column('device_info', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_table_comment(
        'login_histories',
        'Append-only style log of login events. Used for security audits and\n"last login" displays. Prefer INSERT only; do not update historical rows.',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_login_histories_id'), table_name='login_histories')
    op.create_index(op.f('idx_login_histories_user'), 'login_histories', ['user_id', sa.literal_column('login_at DESC')], unique=False)
    op.drop_column('login_histories', 'status')
    op.drop_column('login_histories', 'device')
    op.drop_column('login_histories', 'logout_time')
    op.drop_column('login_histories', 'login_time')
    op.add_column('invoices', sa.Column('tenant_profile_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('notes', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('invoice_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='Generate uniquely per organization, e.g. INV-{YEAR}-{SEQ}. Add unique index per org if needed.'))
    op.create_table_comment(
        'invoices',
        'Monthly (or custom-period) rent bill for a tenant under an agreement.\nFormula: total_amount = rent_amount + utility_charges + late_fees - discount\nWhen recording a COMPLETED payment:\n  paid_amount += payment.amount\n  if paid_amount == 0 â†’ UNPAID\n  if 0 < paid_amount < total â†’ PARTIALLY_PAID\n  if paid_amount >= total â†’ PAID\nScheduler: if due_date < today and status in (UNPAID, PARTIALLY_PAID) â†’ OVERDUE\nVOID invoices are excluded from revenue reports.\nReports page aggregates SUM(paid_amount) / status by date from this table.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key(op.f('invoices_updated_by_fkey'), 'invoices', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('invoices_tenant_profile_id_fkey'), 'invoices', 'tenant_profiles', ['tenant_profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('invoices_created_by_fkey'), 'invoices', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'invoices', type_='unique')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.create_index(op.f('uq_invoice_number'), 'invoices', ['invoice_number'], unique=True, postgresql_where='((invoice_number IS NOT NULL) AND (deleted_at IS NULL))')
    op.create_index(op.f('idx_invoices_tenant'), 'invoices', ['tenant_profile_id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_invoices_status'), 'invoices', ['status'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_invoices_period'), 'invoices', ['billing_period_start', 'billing_period_end'], unique=False)
    op.create_index(op.f('idx_invoices_due_date'), 'invoices', ['due_date'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_invoices_agreement'), 'invoices', ['agreement_id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.alter_column('invoices', 'pdf_url',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('invoices', 'paid_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('invoices', 'total_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('invoices', 'discount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('invoices', 'late_fees',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('invoices', 'utility_charges',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('invoices', 'rent_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    op.drop_column('invoices', 'invoice_date')
    op.drop_column('invoices', 'invoice_no')
    op.drop_column('invoices', 'tenant_id')
    op.add_column('floors', sa.Column('label', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_table_comment(
        'floors',
        'Level inside a property. Unique (property_id, floor_number) prevents duplicates.\nDeleting a property cascades to floors â†’ rooms â†’ beds.',
        existing_comment=None,
        schema=None
    )
    op.create_foreign_key(op.f('floors_updated_by_fkey'), 'floors', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('floors_created_by_fkey'), 'floors', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_floors_id'), table_name='floors')
    op.create_unique_constraint(op.f('uq_floor_per_property'), 'floors', ['property_id', 'floor_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_floors_property'), 'floors', ['property_id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.drop_column('floors', 'status')
    op.drop_column('floors', 'description')
    op.drop_column('floors', 'floor_type')
    op.drop_column('floors', 'floor_name')
    op.add_column('expenses', sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('expenses', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('expenses', sa.Column('vendor_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.create_table_comment(
        'expenses',
        'Operating costs per property (maintenance, utilities, marketing, tax, etc.).\nReports net income â‰ˆ SUM(invoice paid) - SUM(expenses) - SUM(staff salaries).\nModel exists in backend but APIs are not wired yet â€” implement CRUD against this table.',
        existing_comment=None,
        schema=None
    )
    op.create_foreign_key(op.f('expenses_updated_by_fkey'), 'expenses', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('expenses_organization_id_fkey'), 'expenses', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.create_index(op.f('idx_expenses_property'), 'expenses', ['property_id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_expenses_date'), 'expenses', [sa.literal_column('date DESC')], unique=False)
    op.create_index(op.f('idx_expenses_category'), 'expenses', ['category'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.alter_column('expenses', 'receipt_url',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('expenses', 'amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    op.drop_column('expenses', 'payment_mode')
    op.drop_column('expenses', 'expense_date')
    op.add_column('complaints', sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('complaints', sa.Column('tenant_profile_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('complaints', sa.Column('assigned_staff_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('complaints', sa.Column('closed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('complaints', sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_table_comment(
        'complaints',
        'Tenant (or staff) reported issue against a property.\nproperty_id is REQUIRED (where is the problem?).\ntenant_profile_id is optional (staff can log walk-in issues).\nImages â†’ media_files (owner_type=COMPLAINT).\nEvery status change MUST insert a complaint_timelines row.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.create_foreign_key(op.f('complaints_created_by_fkey'), 'complaints', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('complaints_updated_by_fkey'), 'complaints', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('complaints_tenant_profile_id_fkey'), 'complaints', 'tenant_profiles', ['tenant_profile_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('complaints_assigned_staff_id_fkey'), 'complaints', 'users', ['assigned_staff_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_complaints_id'), table_name='complaints')
    op.create_index(op.f('idx_complaints_tenant'), 'complaints', ['tenant_profile_id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_complaints_status'), 'complaints', ['status'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_complaints_property'), 'complaints', ['property_id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_complaints_priority'), 'complaints', ['priority'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_complaints_assigned'), 'complaints', ['assigned_staff_id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.alter_column('complaints', 'description',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)
    op.alter_column('complaints', 'property_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('complaints', 'subject')
    op.drop_column('complaints', 'room_id')
    op.drop_column('complaints', 'staff_id')
    op.drop_column('complaints', 'tenant_id')
    op.add_column('complaint_timelines', sa.Column('changed_by', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('complaint_timelines', sa.Column('to_status', postgresql.ENUM('OPEN', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='complaint_status_enum'), autoincrement=False, nullable=False))
    op.add_column('complaint_timelines', sa.Column('remarks', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('complaint_timelines', sa.Column('from_status', postgresql.ENUM('OPEN', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='complaint_status_enum'), autoincrement=False, nullable=True))
    op.create_table_comment(
        'complaint_timelines',
        'Immutable history of complaint status transitions.\nExample flow: NULLâ†’OPEN â†’ ASSIGNED â†’ IN_PROGRESS â†’ RESOLVED â†’ CLOSED.\nDo not edit old rows; insert new ones. UI "activity feed" reads this table.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'complaint_timelines', type_='foreignkey')
    op.create_foreign_key(op.f('complaint_timelines_changed_by_fkey'), 'complaint_timelines', 'users', ['changed_by'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_complaint_timelines_id'), table_name='complaint_timelines')
    op.create_index(op.f('idx_complaint_timelines_complaint'), 'complaint_timelines', ['complaint_id', 'created_at'], unique=False)
    op.drop_column('complaint_timelines', 'status_update')
    op.drop_column('complaint_timelines', 'message')
    op.drop_column('complaint_timelines', 'staff_id')
    op.add_column('beds', sa.Column('notes', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_table_comment(
        'beds',
        'Smallest rentable unit. One ACTIVE tenant can occupy one bed at a time.\nOn check-in: set status=OCCUPIED and tenant_profiles.bed_id = this id.\nOn check-out: set VACANT and clear tenant_profiles.bed_id.\nNever assign a bed that is MAINTENANCE or already OCCUPIED.',
        existing_comment=None,
        schema=None
    )
    op.create_foreign_key(op.f('beds_created_by_fkey'), 'beds', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('beds_updated_by_fkey'), 'beds', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_beds_id'), table_name='beds')
    op.create_unique_constraint(op.f('uq_bed_per_room'), 'beds', ['room_id', 'bed_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_beds_status'), 'beds', ['status'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_beds_room'), 'beds', ['room_id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.drop_column('beds', 'bed_type')
    op.add_column('audit_logs', sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('user_agent', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_table_comment(
        'audit_logs',
        'Security & compliance trail. Insert on CREATE/UPDATE/DELETE/LOGIN/EXPORT.\nStore old_values/new_values as JSON diffs of changed fields.\nNever update or delete these rows in normal app flow.\nUseful for "who changed this invoice?" and regulatory audits.',
        existing_comment=None,
        schema=None
    )
    op.create_foreign_key(op.f('audit_logs_organization_id_fkey'), 'audit_logs', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.create_index(op.f('idx_audit_logs_user'), 'audit_logs', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_audit_logs_table_record'), 'audit_logs', ['table_name', 'record_id'], unique=False)
    op.create_index(op.f('idx_audit_logs_created'), 'audit_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('audit_logs', 'new_values',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_logs', 'old_values',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('audit_logs', 'updated_by')
    op.drop_column('audit_logs', 'created_by')
    op.drop_column('audit_logs', 'deleted_at')
    op.drop_column('audit_logs', 'updated_at')
    op.add_column('agreements', sa.Column('terms_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('agreements', sa.Column('terminated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('agreements', sa.Column('tenant_profile_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('agreements', sa.Column('notice_period_days', sa.INTEGER(), server_default=sa.text('30'), autoincrement=False, nullable=True))
    op.add_column('agreements', sa.Column('security_deposit', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('agreements', sa.Column('billing_day', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True))
    op.add_column('agreements', sa.Column('terminated_reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_table_comment(
        'agreements',
        'Lease contract between tenant and property for a specific bed/room.\nSnapshots bed_id + room_id so history survives if tenant moves beds.\nOnly one ACTIVE agreement per tenant is recommended (enforce in app or\npartial unique index if you want DB-level guarantee).\nInvoices MUST reference an agreement.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'agreements', type_='foreignkey')
    op.create_foreign_key(op.f('agreements_created_by_fkey'), 'agreements', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('agreements_tenant_profile_id_fkey'), 'agreements', 'tenant_profiles', ['tenant_profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('agreements_updated_by_fkey'), 'agreements', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'agreements', type_='unique')
    op.drop_index(op.f('ix_agreements_id'), table_name='agreements')
    op.create_index(op.f('uq_one_active_agreement_per_tenant'), 'agreements', ['tenant_profile_id'], unique=True, postgresql_where="((status = 'ACTIVE'::agreement_status_enum) AND (deleted_at IS NULL))")
    op.create_index(op.f('idx_agreements_tenant'), 'agreements', ['tenant_profile_id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_agreements_status'), 'agreements', ['status'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_agreements_dates'), 'agreements', ['start_date', 'end_date'], unique=False)
    op.alter_column('agreements', 'agreement_pdf_url',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('agreements', 'rent_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    op.drop_column('agreements', 'terms')
    op.drop_column('agreements', 'deposit_amount')
    op.drop_column('agreements', 'agreement_no')
    op.drop_column('agreements', 'tenant_id')
    op.create_table('auth_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('refresh_jti', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('auth_sessions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('auth_sessions_pkey')),
    sa.UniqueConstraint('session_id', name=op.f('uq_auth_sessions_sid'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='Tracks JWT sessions. On logout set revoked_at. Access tokens with matching\nsid must be rejected after revoke. Replaces the in-memory Redis blacklist\nso multi-instance backends stay consistent.'
    )
    op.create_index(op.f('idx_auth_sessions_user'), 'auth_sessions', ['user_id'], unique=False)
    op.create_index(op.f('idx_auth_sessions_expires'), 'auth_sessions', ['expires_at'], unique=False)
    # ### end Alembic commands ###
