"""Add new field

Revision ID: a3ac62d0f276
Revises: f75cb127cbe0
Create Date: 2026-07-31 11:50:16.790905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3ac62d0f276'
down_revision: Union[str, None] = 'f75cb127cbe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('agreements_bed_id_fkey'), 'agreements', type_='foreignkey')
    op.drop_constraint(op.f('agreements_room_id_fkey'), 'agreements', type_='foreignkey')
    op.drop_column('agreements', 'bed_id')
    op.drop_column('agreements', 'agreement_pdf_url')
    op.drop_column('agreements', 'status')
    op.drop_column('agreements', 'room_id')
    op.drop_column('complaints', 'images')
    op.drop_column('complaints', 'category')
    op.drop_column('expenses', 'receipt_url')
    op.drop_constraint(op.f('invoices_agreement_id_fkey'), 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'discount')
    op.drop_column('invoices', 'billing_period_start')
    op.drop_column('invoices', 'agreement_id')
    op.drop_column('invoices', 'utility_charges')
    op.drop_column('invoices', 'billing_period_end')
    op.drop_column('invoices', 'rent_amount')
    op.drop_column('invoices', 'pdf_url')
    op.drop_column('invoices', 'late_fees')
    op.drop_column('notification_logs', 'error_message')
    op.drop_column('notification_logs', 'status')
    op.drop_column('notification_logs', 'retry_count')
    op.drop_column('notification_logs', 'sent_at')
    op.drop_column('properties', 'images')
    op.drop_column('properties', 'documents')
    op.drop_column('properties', 'description')
    op.drop_column('rent_reminders', 'sent_at')
    op.drop_column('staff_profiles', 'documents')
    op.drop_column('staff_profiles', 'photo_url')
    op.drop_column('staff_salaries', 'payment_mode')
    op.drop_column('staff_salaries', 'status')
    op.drop_column('tenant_profiles', 'aadhaar_number')
    op.drop_column('tenant_profiles', 'photo_url')
    op.drop_column('tenant_profiles', 'passport_number')
    op.drop_column('tenant_profiles', 'pan_number')
    op.drop_column('tenant_profiles', 'driving_license')
    op.drop_column('tenant_profiles', 'check_out_date')
    op.drop_column('tenant_profiles', 'emergency_contact')
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=False, server_default='default_hash'))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'phone')
    op.add_column('tenant_profiles', sa.Column('emergency_contact', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('tenant_profiles', sa.Column('check_out_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('tenant_profiles', sa.Column('driving_license', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('tenant_profiles', sa.Column('pan_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('tenant_profiles', sa.Column('passport_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('tenant_profiles', sa.Column('photo_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('tenant_profiles', sa.Column('aadhaar_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('staff_salaries', sa.Column('status', postgresql.ENUM('PENDING', 'PAID', 'HOLD', name='salary_status_enum'), server_default=sa.text("'PENDING'::salary_status_enum"), autoincrement=False, nullable=False))
    op.add_column('staff_salaries', sa.Column('payment_mode', postgresql.ENUM('CASH', 'BANK_TRANSFER', 'CHEQUE', 'UPI', name='staff_payment_mode_enum'), autoincrement=False, nullable=True))
    op.add_column('staff_profiles', sa.Column('photo_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('staff_profiles', sa.Column('documents', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=True))
    op.add_column('rent_reminders', sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('documents', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('images', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=True))
    op.add_column('notification_logs', sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('notification_logs', sa.Column('retry_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('notification_logs', sa.Column('status', postgresql.ENUM('PENDING', 'SENT', 'FAILED', name='notification_status_enum'), server_default=sa.text("'PENDING'::notification_status_enum"), autoincrement=False, nullable=False))
    op.add_column('notification_logs', sa.Column('error_message', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('late_fees', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('pdf_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('rent_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('billing_period_end', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('utility_charges', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('agreement_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('billing_period_start', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('discount', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('invoices_agreement_id_fkey'), 'invoices', 'agreements', ['agreement_id'], ['id'], ondelete='CASCADE')
    op.add_column('expenses', sa.Column('receipt_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('complaints', sa.Column('category', postgresql.ENUM('PLUMBING', 'ELECTRICAL', 'APPLIANCE', 'CLEANING', 'SECURITY', 'OTHER', name='complaint_category_enum'), server_default=sa.text("'OTHER'::complaint_category_enum"), autoincrement=False, nullable=False))
    op.add_column('complaints', sa.Column('images', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=True))
    op.add_column('agreements', sa.Column('room_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('agreements', sa.Column('status', postgresql.ENUM('ACTIVE', 'EXPIRED', 'TERMINATED', name='agreement_status_enum'), server_default=sa.text("'ACTIVE'::agreement_status_enum"), autoincrement=False, nullable=False))
    op.add_column('agreements', sa.Column('agreement_pdf_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('agreements', sa.Column('bed_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('agreements_room_id_fkey'), 'agreements', 'rooms', ['room_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('agreements_bed_id_fkey'), 'agreements', 'beds', ['bed_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
