"""add status to agreements

Revision ID: c9d9fe81175e
Revises: 4aa9dbbd8e77
Create Date: 2026-08-04 09:54:51.370019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9d9fe81175e'
down_revision: Union[str, None] = '4aa9dbbd8e77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agreements', sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'TERMINATED', name='agreement_status_enum'), nullable=False, server_default='ACTIVE'))
    op.alter_column('agreements', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agreements', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('agreements', 'status')
    # ### end Alembic commands ###
