"""create users table

Revision ID: d1b1ff547d07
Revises: d7be3d155e65
Create Date: 2026-08-10 10:31:29.895407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1b1ff547d07'
down_revision: Union[str, None] = 'd7be3d155e65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chk_agreement_dates'), 'agreements', type_='check')
    op.drop_constraint(op.f('chk_agreement_rent_nonneg'), 'agreements', type_='check')
    op.drop_constraint(op.f('chk_expense_amount_positive'), 'expenses', type_='check')
    op.drop_constraint(op.f('chk_invoice_paid_lte_total'), 'invoices', type_='check')
    op.drop_constraint(op.f('chk_payment_amount_positive'), 'payments', type_='check')
    op.drop_column('properties', 'total_floors')
    op.drop_constraint(op.f('chk_attendance_checkout_after_checkin'), 'staff_attendances', type_='check')
    op.drop_constraint(op.f('chk_staff_salary_nonneg'), 'staff_profiles', type_='check')
    op.drop_constraint(op.f('chk_salary_month'), 'staff_salaries', type_='check')
    op.drop_constraint(op.f('chk_salary_year'), 'staff_salaries', type_='check')
    op.drop_constraint(op.f('chk_tenant_deposit_nonneg'), 'tenant_profiles', type_='check')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(op.f('chk_tenant_deposit_nonneg'), 'tenant_profiles', 'security_deposit >= 0::numeric')
    op.create_check_constraint(op.f('chk_salary_year'), 'staff_salaries', 'year >= 2020')
    op.create_check_constraint(op.f('chk_salary_month'), 'staff_salaries', 'month >= 1 AND month <= 12')
    op.create_check_constraint(op.f('chk_staff_salary_nonneg'), 'staff_profiles', 'salary >= 0::numeric')
    op.create_check_constraint(op.f('chk_attendance_checkout_after_checkin'), 'staff_attendances', 'check_out IS NULL OR check_in IS NULL OR check_out >= check_in')
    op.add_column('properties', sa.Column('total_floors', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.create_check_constraint(op.f('chk_payment_amount_positive'), 'payments', 'amount > 0::numeric')
    op.create_check_constraint(op.f('chk_invoice_paid_lte_total'), 'invoices', 'paid_amount <= total_amount')
    op.create_check_constraint(op.f('chk_expense_amount_positive'), 'expenses', 'amount > 0::numeric')
    op.create_check_constraint(op.f('chk_agreement_rent_nonneg'), 'agreements', 'rent_amount >= 0::numeric')
    op.create_check_constraint(op.f('chk_agreement_dates'), 'agreements', 'end_date >= start_date')
    # ### end Alembic commands ###
