"""add total_floors to property

Revision ID: d7be3d155e65
Revises: fa62798bd6f7
Create Date: 2026-08-06 17:56:28.540370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7be3d155e65'
down_revision: Union[str, None] = 'fa62798bd6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_room_histories_event_type'), table_name='room_histories')
    op.drop_index(op.f('ix_room_histories_id'), table_name='room_histories')
    op.drop_index(op.f('ix_room_histories_property_id'), table_name='room_histories')
    op.drop_index(op.f('ix_room_histories_room_id'), table_name='room_histories')
    op.drop_table('room_histories')
    op.drop_constraint(op.f('beds_tenant_id_fkey'), 'beds', type_='foreignkey')
    op.drop_column('beds', 'tenant_id')
    op.drop_column('beds', 'bed_name')
    op.drop_column('beds', 'is_active')
    op.add_column('properties', sa.Column('total_floors', sa.Integer(), nullable=False))
    op.alter_column('rooms', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_rooms_property_id'), table_name='rooms')
    op.drop_constraint(op.f('rooms_property_id_fkey'), 'rooms', type_='foreignkey')
    op.drop_column('rooms', 'property_id')
    op.drop_column('tenant_profiles', 'check_in_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_profiles', sa.Column('check_in_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('property_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('rooms_property_id_fkey'), 'rooms', 'properties', ['property_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_rooms_property_id'), 'rooms', ['property_id'], unique=False)
    op.alter_column('rooms', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.drop_column('properties', 'total_floors')
    op.add_column('beds', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('beds', sa.Column('bed_name', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('beds', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('beds_tenant_id_fkey'), 'beds', 'tenant_profiles', ['tenant_id'], ['id'], ondelete='SET NULL')
    op.create_table('room_histories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('room_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('property_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('floor_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('bed_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('event_type', postgresql.ENUM('ROOM_CREATED', 'ROOM_UPDATED', 'ROOM_DELETED', 'BED_ADDED', 'BED_REMOVED', 'BED_STATUS_CHANGED', 'TENANT_ASSIGNED', 'TENANT_TRANSFER', 'TENANT_CHECKOUT', 'MAINTENANCE_SET', 'CAPACITY_INCREASED', 'CAPACITY_DECREASED', 'FLOOR_CREATED', 'FLOOR_UPDATED', name='history_event_type_enum'), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('old_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('new_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('performed_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], name=op.f('room_histories_floor_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('room_histories_property_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('room_histories_room_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('room_histories_pkey'))
    )
    op.create_index(op.f('ix_room_histories_room_id'), 'room_histories', ['room_id'], unique=False)
    op.create_index(op.f('ix_room_histories_property_id'), 'room_histories', ['property_id'], unique=False)
    op.create_index(op.f('ix_room_histories_id'), 'room_histories', ['id'], unique=False)
    op.create_index(op.f('ix_room_histories_event_type'), 'room_histories', ['event_type'], unique=False)
    # ### end Alembic commands ###
