"""added automated billing fields

Revision ID: dea48b94f199
Revises: aef3cb912fe4
Create Date: 2026-08-01 12:52:02.379932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dea48b94f199'
down_revision: Union[str, None] = 'aef3cb912fe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE tenant_status_enum ADD VALUE IF NOT EXISTS 'NOTICE'")
    op.execute("ALTER TYPE tenant_status_enum ADD VALUE IF NOT EXISTS 'CHECKED_OUT'")
    op.execute("ALTER TYPE invoice_status_enum ADD VALUE IF NOT EXISTS 'PENDING'")
    op.execute("ALTER TYPE payment_status_enum ADD VALUE IF NOT EXISTS 'PENDING_VERIFICATION'")
    op.execute("ALTER TYPE payment_status_enum ADD VALUE IF NOT EXISTS 'SUCCESS'")
    op.execute("ALTER TYPE payment_status_enum ADD VALUE IF NOT EXISTS 'REJECTED'")
    op.execute("COMMIT")
    
    # Update existing records to new enums to avoid issues
    op.execute("UPDATE invoices SET status = 'PENDING' WHERE status = 'UNPAID'")
    op.execute("UPDATE payments SET status = 'PENDING_VERIFICATION' WHERE status = 'PENDING'")
    op.execute("UPDATE payments SET status = 'SUCCESS' WHERE status = 'COMPLETED'")
    op.execute("UPDATE payments SET status = 'REJECTED' WHERE status = 'FAILED'")
    op.create_table('payment_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('upi_id', sa.String(length=100), nullable=False),
    sa.Column('account_holder', sa.String(length=100), nullable=False),
    sa.Column('qr_code_image', sa.String(length=255), nullable=True),
    sa.Column('payment_instruction', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('invoices', sa.Column('billing_start_date', sa.Date(), nullable=False))
    op.add_column('invoices', sa.Column('billing_end_date', sa.Date(), nullable=False))
    op.add_column('payments', sa.Column('payment_proof', sa.String(length=255), nullable=True))
    op.add_column('payments', sa.Column('remarks', sa.String(length=255), nullable=True))
    op.add_column('tenant_profiles', sa.Column('check_out_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_profiles', 'check_out_date')
    op.drop_column('payments', 'remarks')
    op.drop_column('payments', 'payment_proof')
    op.drop_column('invoices', 'billing_end_date')
    op.drop_column('invoices', 'billing_start_date')
    op.drop_table('payment_settings')
    # ### end Alembic commands ###
