"""add tenant profile fields

Revision ID: fa62798bd6f7
Revises: 610269dcc5d9
Create Date: 2026-08-06 15:34:31.441023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa62798bd6f7'
down_revision: Union[str, None] = '610269dcc5d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_profiles', sa.Column('guardian_relation', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('nationality', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('occupation', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'occupation')
    op.drop_column('users', 'nationality')
    op.drop_column('tenant_profiles', 'guardian_relation')
    # ### end Alembic commands ###
